{% set name = "kaitaistruct" %}
{% set version = "0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kaitaistruct-{{ version }}.tar.gz
  sha256: a044dee29173d6afbacf27bcac39daf89b654dd418cfa009ab82d9178a9ae52a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - kaitaistruct
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://kaitai.io
  summary: 'Kaitai Struct declarative parser generator for binary data: runtime library for Python'
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jonashaag
    - AdrianFreundQC
    - freundTech
